package org.jbxbase.domain;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tuser.id
	 * @mbggenerated  Mon Sep 01 13:36:59 CST 2014
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tuser.createdatetime
	 * @mbggenerated  Mon Sep 01 13:36:59 CST 2014
	 */
	private Date createdatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tuser.name
	 * @mbggenerated  Mon Sep 01 13:36:59 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tuser.pwd
	 * @mbggenerated  Mon Sep 01 13:36:59 CST 2014
	 */
	private String pwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tuser.modifydatetime
	 * @mbggenerated  Mon Sep 01 13:36:59 CST 2014
	 */
	private Date modifydatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tuser.CREATE_TIME
	 * @mbggenerated  Mon Sep 01 13:36:59 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tuser.UPDATE_TIME
	 * @mbggenerated  Mon Sep 01 13:36:59 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tuser.id
	 * @return  the value of tuser.id
	 * @mbggenerated  Mon Sep 01 13:36:59 CST 2014
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tuser.id
	 * @param id  the value for tuser.id
	 * @mbggenerated  Mon Sep 01 13:36:59 CST 2014
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tuser.createdatetime
	 * @return  the value of tuser.createdatetime
	 * @mbggenerated  Mon Sep 01 13:36:59 CST 2014
	 */
	public Date getCreatedatetime() {
		return createdatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tuser.createdatetime
	 * @param createdatetime  the value for tuser.createdatetime
	 * @mbggenerated  Mon Sep 01 13:36:59 CST 2014
	 */
	public void setCreatedatetime(Date createdatetime) {
		this.createdatetime = createdatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tuser.name
	 * @return  the value of tuser.name
	 * @mbggenerated  Mon Sep 01 13:36:59 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tuser.name
	 * @param name  the value for tuser.name
	 * @mbggenerated  Mon Sep 01 13:36:59 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tuser.pwd
	 * @return  the value of tuser.pwd
	 * @mbggenerated  Mon Sep 01 13:36:59 CST 2014
	 */
	public String getPwd() {
		return pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tuser.pwd
	 * @param pwd  the value for tuser.pwd
	 * @mbggenerated  Mon Sep 01 13:36:59 CST 2014
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tuser.modifydatetime
	 * @return  the value of tuser.modifydatetime
	 * @mbggenerated  Mon Sep 01 13:36:59 CST 2014
	 */
	public Date getModifydatetime() {
		return modifydatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tuser.modifydatetime
	 * @param modifydatetime  the value for tuser.modifydatetime
	 * @mbggenerated  Mon Sep 01 13:36:59 CST 2014
	 */
	public void setModifydatetime(Date modifydatetime) {
		this.modifydatetime = modifydatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tuser.CREATE_TIME
	 * @return  the value of tuser.CREATE_TIME
	 * @mbggenerated  Mon Sep 01 13:36:59 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tuser.CREATE_TIME
	 * @param createTime  the value for tuser.CREATE_TIME
	 * @mbggenerated  Mon Sep 01 13:36:59 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tuser.UPDATE_TIME
	 * @return  the value of tuser.UPDATE_TIME
	 * @mbggenerated  Mon Sep 01 13:36:59 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tuser.UPDATE_TIME
	 * @param updateTime  the value for tuser.UPDATE_TIME
	 * @mbggenerated  Mon Sep 01 13:36:59 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}