CREATE TABLE `weatherenv` (
`id`  bigint(50) NOT NULL AUTO_INCREMENT ,
`areacity`  varchar(200) NULL ,
`weather`  varchar(255) NULL ,
`weatherDay`  varchar(255) NULL ,
`weatherNight`  varchar(255) NULL ,
`temperatureCurr`  varchar(255) NULL ,
`temperatureRange`  varchar(255) NULL ,
`humility`  varchar(255) NULL ,
`pressure`  varchar(255) NULL ,
`windDir`  varchar(255) NULL ,
`windSpeed`  varchar(255) NULL ,
`sunUp`  varchar(255) NULL ,
`sunSet`  varchar(255) NULL ,
`ultraviolet`  varchar(255) NULL ,
`aqi`  varchar(255) NULL ,
`pm25`  varchar(255) NULL ,
`pm10`  varchar(255) NULL ,
`so2`  varchar(255) NULL ,
`no2`  varchar(255) NULL ,
`co`  varchar(255) NULL ,
`o3`  varchar(255) NULL ,
`updateTime` datetime NULL ,
PRIMARY KEY (`id`)
);