/*操作权限对应的英文名称补齐*/
UPDATE reliprivilege SET privilege_name_en = 'Netvox Cloud Platform' WHERE id = 1001;
UPDATE reliprivilege SET privilege_name_en = 'Remote online upgrading' WHERE id = 1002;
UPDATE reliprivilege SET privilege_name_en = 'Software version upgrading management' WHERE id = 1003;
UPDATE reliprivilege SET privilege_name_en = 'Add' WHERE id = 1004;
UPDATE reliprivilege SET privilege_name_en = 'Edit' WHERE id = 1005;
UPDATE reliprivilege SET privilege_name_en = 'Delete' WHERE id = 1006;
UPDATE reliprivilege SET privilege_name_en = 'Hardware version management' WHERE id = 1007;
UPDATE reliprivilege SET privilege_name_en = 'Add' WHERE id = 1008;
UPDATE reliprivilege SET privilege_name_en = 'Edit' WHERE id = 1009;
UPDATE reliprivilege SET privilege_name_en = 'Delete' WHERE id = 1010;
UPDATE reliprivilege SET privilege_name_en = 'Household registration management' WHERE id = 1011;
UPDATE reliprivilege SET privilege_name_en = 'Check for details' WHERE id = 1012;
UPDATE reliprivilege SET privilege_name_en = 'Edit' WHERE id = 1013;
UPDATE reliprivilege SET privilege_name_en = 'Delete' WHERE id = 1014;
UPDATE reliprivilege SET privilege_name_en = 'Register new accounts' WHERE id = 1015;
UPDATE reliprivilege SET privilege_name_en = 'Register in bulk' WHERE id = 1017;
UPDATE reliprivilege SET privilege_name_en = 'Transfer in bulk' WHERE id = 1018;
UPDATE reliprivilege SET privilege_name_en = 'Cloud service management' WHERE id = 1019;
UPDATE reliprivilege SET privilege_name_en = 'Monitor SHC services' WHERE id = 1020;
UPDATE reliprivilege SET privilege_name_en = 'Open' WHERE id = 1021;
UPDATE reliprivilege SET privilege_name_en = 'Close' WHERE id = 1022;
UPDATE reliprivilege SET privilege_name_en = 'Administrator email setting' WHERE id = 1023;
UPDATE reliprivilege SET privilege_name_en = 'Monitoring log' WHERE id = 1025;
UPDATE reliprivilege SET privilege_name_en = 'Browse' WHERE id = 1026;
UPDATE reliprivilege SET privilege_name_en = 'Export' WHERE id = 1027;
UPDATE reliprivilege SET privilege_name_en = 'Outing management' WHERE id = 1028;
UPDATE reliprivilege SET privilege_name_en = 'Open' WHERE id = 1029;
UPDATE reliprivilege SET privilege_name_en = 'Close' WHERE id = 1030;
UPDATE reliprivilege SET privilege_name_en = 'Alarm video storage' WHERE id = 1031;
UPDATE reliprivilege SET privilege_name_en = 'Open' WHERE id = 1032;
UPDATE reliprivilege SET privilege_name_en = 'Cloase' WHERE id = 1033;
UPDATE reliprivilege SET privilege_name_en = 'LQI threshold setting' WHERE id = 1034;
UPDATE reliprivilege SET privilege_name_en = 'Open' WHERE id = 1035;
UPDATE reliprivilege SET privilege_name_en = 'Close' WHERE id = 1036;
UPDATE reliprivilege SET privilege_name_en = 'LQI threshold setting' WHERE id = 1037;
UPDATE reliprivilege SET privilege_name_en = 'Time of starting LQI check' WHERE id = 1038;
UPDATE reliprivilege SET privilege_name_en = 'Send the online status of device to the cloud' WHERE id = 1039;
UPDATE reliprivilege SET privilege_name_en = 'Open' WHERE id = 1040;
UPDATE reliprivilege SET privilege_name_en = 'Close' WHERE id = 1041;
UPDATE reliprivilege SET privilege_name_en = 'Send advertising address' WHERE id = 1042;
UPDATE reliprivilege SET privilege_name_en = 'Management' WHERE id = 1043;
UPDATE reliprivilege SET privilege_name_en = 'Setting' WHERE id = 1044;
UPDATE reliprivilege SET privilege_name_en = 'Send pre-alarm in short message or email ' WHERE id = 1045;
UPDATE reliprivilege SET privilege_name_en = 'Open' WHERE id = 1046;
UPDATE reliprivilege SET privilege_name_en = 'Close' WHERE id = 1047;
UPDATE reliprivilege SET privilege_name_en = 'Send systematic information' WHERE id = 1048;
UPDATE reliprivilege SET privilege_name_en = 'Reliability platform' WHERE id = 1049;
UPDATE reliprivilege SET privilege_name_en = 'HOusehold profile' WHERE id = 1050;
UPDATE reliprivilege SET privilege_name_en = 'Map distribution ' WHERE id = 1051;
UPDATE reliprivilege SET privilege_name_en = 'Check for details' WHERE id = 1052;
UPDATE reliprivilege SET privilege_name_en = 'Manual upgrading ' WHERE id = 1053;
UPDATE reliprivilege SET privilege_name_en = 'APP check and statistics' WHERE id = 1054;
UPDATE reliprivilege SET privilege_name_en = 'Device status list' WHERE id = 1055;
UPDATE reliprivilege SET privilege_name_en = 'Device attribute report' WHERE id = 1056;
UPDATE reliprivilege SET privilege_name_en = 'Export' WHERE id = 1057;
UPDATE reliprivilege SET privilege_name_en = 'Operational history list' WHERE id = 1058;
UPDATE reliprivilege SET privilege_name_en = 'Check the designated action' WHERE id = 1059;
UPDATE reliprivilege SET privilege_name_en = 'Check device log' WHERE id = 1060;

UPDATE reliprivilege SET privilege_name_en = 'Check the log of designated action' WHERE id = 1061;
UPDATE reliprivilege SET privilege_name_en = 'Alarm history list' WHERE id = 1062;
UPDATE reliprivilege SET privilege_name_en = 'List of network communication quality' WHERE id = 1063;
UPDATE reliprivilege SET privilege_name_en = 'List of monitoring log' WHERE id = 1064;
UPDATE reliprivilege SET privilege_name_en = 'Browse and view' WHERE id = 1065;
UPDATE reliprivilege SET privilege_name_en = 'Export' WHERE id = 1066;
UPDATE reliprivilege SET privilege_name_en = 'Short message/email setting' WHERE id = 1067;
UPDATE reliprivilege SET privilege_name_en = 'Pre-alarm phone' WHERE id = 1068;
UPDATE reliprivilege SET privilege_name_en = 'Add' WHERE id = 1069;
UPDATE reliprivilege SET privilege_name_en = 'Display' WHERE id = 1070;
UPDATE reliprivilege SET privilege_name_en = 'Delete' WHERE id = 1071;
UPDATE reliprivilege SET privilege_name_en = 'Pre-alarm email' WHERE id = 1072;
UPDATE reliprivilege SET privilege_name_en = 'Add' WHERE id = 1073;
UPDATE reliprivilege SET privilege_name_en = 'Display' WHERE id = 1074;
UPDATE reliprivilege SET privilege_name_en = 'Delete' WHERE id = 1075;
UPDATE reliprivilege SET privilege_name_en = 'CSHC data statistics' WHERE id = 1076;
UPDATE reliprivilege SET privilege_name_en = 'Heartbeat statistics' WHERE id = 1077;
UPDATE reliprivilege SET privilege_name_en = 'Browse and view' WHERE id = 1078;
UPDATE reliprivilege SET privilege_name_en = 'Export' WHERE id = 1079;
UPDATE reliprivilege SET privilege_name_en = 'Battery voltage statistics' WHERE id = 1080;
UPDATE reliprivilege SET privilege_name_en = 'Browse and view' WHERE id = 1081;
UPDATE reliprivilege SET privilege_name_en = 'Export' WHERE id = 1082;
UPDATE reliprivilege SET privilege_name_en = 'Energy related statistics' WHERE id = 1083;
UPDATE reliprivilege SET privilege_name_en = 'Browse and view' WHERE id = 1084;
UPDATE reliprivilege SET privilege_name_en = 'Export' WHERE id = 1085;
UPDATE reliprivilege SET privilege_name_en = 'Cloud IR library management' WHERE id = 1086;
UPDATE reliprivilege SET privilege_name_en = 'Import' WHERE id = 1087;
UPDATE reliprivilege SET privilege_name_en = 'Authentication' WHERE id = 1088;
UPDATE reliprivilege SET privilege_name_en = 'Edit' WHERE id = 1089;
UPDATE reliprivilege SET privilege_name_en = 'Delete' WHERE id = 1090;
UPDATE reliprivilege SET privilege_name_en = 'Download' WHERE id = 1091;
UPDATE reliprivilege SET privilege_name_en = 'Burnin management' WHERE id = 1092;
UPDATE reliprivilege SET privilege_name_en = 'Management list' WHERE id = 1093;
UPDATE reliprivilege SET privilege_name_en = 'Add' WHERE id = 1094;
UPDATE reliprivilege SET privilege_name_en = 'Open' WHERE id = 1095;
UPDATE reliprivilege SET privilege_name_en = 'Close' WHERE id = 1096;
UPDATE reliprivilege SET privilege_name_en = 'Initialize' WHERE id = 1097;
UPDATE reliprivilege SET privilege_name_en = 'Complete' WHERE id = 1098;
UPDATE reliprivilege SET privilege_name_en = 'Restart' WHERE id = 1099;
UPDATE reliprivilege SET privilege_name_en = 'Interity' WHERE id = 1100;
UPDATE reliprivilege SET privilege_name_en = 'List of abnormal stop' WHERE id = 1101;
UPDATE reliprivilege SET privilege_name_en = 'User management' WHERE id = 1102;
UPDATE reliprivilege SET privilege_name_en = 'Add' WHERE id = 1103;
UPDATE reliprivilege SET privilege_name_en = 'Edit' WHERE id = 1104;
UPDATE reliprivilege SET privilege_name_en = 'Delete' WHERE id = 1105;
UPDATE reliprivilege SET privilege_name_en = 'Empower' WHERE id = 1106;
UPDATE reliprivilege SET privilege_name_en = 'Server management' WHERE id = 1107;
UPDATE reliprivilege SET privilege_name_en = 'Add' WHERE id = 1108;
UPDATE reliprivilege SET privilege_name_en = 'Edit' WHERE id = 1109;
UPDATE reliprivilege SET privilege_name_en = 'Delete' WHERE id = 1110;
UPDATE reliprivilege SET privilege_name_en = 'Burnin sign-on' WHERE id = 1111;
UPDATE reliprivilege SET privilege_name_en = 'Short message history' WHERE id = 1112;
UPDATE reliprivilege SET privilege_name_en = 'Export' WHERE id = 1113;
UPDATE reliprivilege SET privilege_name_en = 'Customer code management' WHERE id = 1114;
UPDATE reliprivilege SET privilege_name_en = 'Add' WHERE id = 1115;
UPDATE reliprivilege SET privilege_name_en = 'Edit' WHERE id = 1116;

UPDATE reliprivilege SET privilege_name_en = 'Delete' WHERE id = 1117;
UPDATE reliprivilege SET privilege_name_en = 'Authority management' WHERE id = 1118;
UPDATE reliprivilege SET privilege_name_en = 'Add' WHERE id = 1119;
UPDATE reliprivilege SET privilege_name_en = 'Edit' WHERE id = 1120;
UPDATE reliprivilege SET privilege_name_en = 'Delete' WHERE id = 1121;
UPDATE reliprivilege SET privilege_name_en = 'Production registration' WHERE id = 1122;
UPDATE reliprivilege SET privilege_name_en = 'App version management' WHERE id = 1123;
UPDATE reliprivilege SET privilege_name_en = 'Add' WHERE id = 1124;
UPDATE reliprivilege SET privilege_name_en = 'Modify' WHERE id = 1125;
UPDATE reliprivilege SET privilege_name_en = 'Delete' WHERE id = 1126;

UPDATE reliprivilege SET privilege_name_en = 'APP crash log' WHERE id = 1127;
UPDATE reliprivilege SET privilege_name_en = 'IR temorary library' WHERE id = 1128;
UPDATE reliprivilege SET privilege_name_en = 'Authentication' WHERE id = 1129;
UPDATE reliprivilege SET privilege_name_en = 'Delete' WHERE id = 1130;
UPDATE reliprivilege SET privilege_name_en = 'APP crash log' WHERE id = 1131;
UPDATE reliprivilege SET privilege_name_en = '485 template library' WHERE id = 1132;
UPDATE reliprivilege SET privilege_name_en = 'Add device types' WHERE id = 1133;
UPDATE reliprivilege SET privilege_name_en = 'Edit' WHERE id = 1134;
UPDATE reliprivilege SET privilege_name_en = 'Delete' WHERE id = 1135;
UPDATE reliprivilege SET privilege_name_en = 'IES management platform' WHERE id = 1136;

UPDATE reliprivilege SET privilege_name_en = 'Add users' WHERE id = 1137;
UPDATE reliprivilege SET privilege_name_en = 'Reset password' WHERE id = 1138;
UPDATE reliprivilege SET privilege_name_en = 'Delete' WHERE id = 1139;
UPDATE reliprivilege SET privilege_name_en = 'Device type' WHERE id = 1140;
UPDATE reliprivilege SET privilege_name_en = 'Device template' WHERE id = 1141;
UPDATE reliprivilege SET privilege_name_en = 'Edit device type ID' WHERE id = 1142;
UPDATE reliprivilege SET privilege_name_en = 'Add device template' WHERE id = 1143;
UPDATE reliprivilege SET privilege_name_en = 'Edit' WHERE id = 1144;
UPDATE reliprivilege SET privilege_name_en = 'Delete' WHERE id = 1145;
